mockStore now passes exceptions.
For example instead of the former meaningless and misleading error reported, you now see
the reason why your tests failed:

fetchPages
    1) creates FETCH_PAGES_SUCCESS when fetching pages has been done

  0 passing (2s)
  1 failing

  1) fetchPages creates FETCH_PAGES_SUCCESS when fetching pages has been done:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

------------------------------------------------------------------------------------------------

fetchPages
    1) creates FETCH_PAGES_SUCCESS when fetching pages has been done

  0 passing (47ms)
  1 failing

  1) fetchPages creates FETCH_PAGES_SUCCESS when fetching pages has been done:

      AssertionError: { type: 'FETCH_PAGES_SUCCESS',
  pages:
   [ { id: '5628946bd0771c0e054ec2d5' },
     { id: '5628946bd0771c0e054ec2d6' } ] } deepEqual { type: 'FETCH_PAGES_SUCCESS', pages: {} }
      + expected - actual

       {
      -  "pages": [
      -    {
      -      "id": "5628946bd0771c0e054ec2d5"
      -    }
      -    {
      -      "id": "5628946bd0771c0e054ec2d6"
      -    }
      -  ]
      +  "pages": {}
         "type": "FETCH_PAGES_SUCCESS"
       }


Former-commit-id: e5fd5cafdb0310d99873268caf1b2dd82a5b58f6
Former-commit-id: ce792e9df1d0bbff7d0e543e133b20ba4d35e059